version: '3'

tasks:
  fmt:
    sources:
      - '*.go'
    cmd: gofmt -w .

  test:
    run: once
    sources:
      - '*.go'
      - go.sum
    cmd: go test ./...

  lint:
    sources:
      - '*.go'
      - go.sum
      - .golangci.yaml
    cmd: go tool golangci-lint run

  check:
    deps:
      - test
      - lint
